spring:
  config:
    import: optional:file:.env
  datasource:
    url: jdbc:postgresql://localhost:5433/urbansoul_db
    username: ${DB_USERNAME:urbansoul}
    password: ${DB_PASSWORD:urbansoul}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

ia:
  service:
    url: ${IA_SERVICE_URL:http://localhost:8000}

jwt:
  secret: 5b3c9f2a8e7d4a1b6f9c3e2d8a5b7f4c1e9d2a6b8f3c5e7d4a1b9f2c8e3d6a5b #${JWT_SECRET:changeme}
  expiration-ms: 86400000
